### PR TITLE
[BUG DEMO] Add a test for secure values in env mapping

### PR DESCRIPTION
**Pull request by webknjaz**
Demonstrates #78 

@svenfuchs could you please verify whether I've made a correct assumption about the issue with parsing `secure:`'s?

### CODE REVIEW

**Comment by webknjaz** [comment]
AFAICS it really matches with behavior I've hit:

```console
$ export scrt={:secure=>
/home/travis/.travis/job_stages: eval: line 104: syntax error near unexpected token `newline'
/home/travis/.travis/job_stages: eval: line 104: `export scrt={:secure=> '
```

```json
{
  "if": "tag IS present",
  "os": "linux",
  "dist": "trusty",
  "sudo": false,
  "cache": {
    "pip": true
  },
  "group": "stable",
  "stage": "upload new version of python package to PYPI (only for tagged commits)",
  "python": 3.6,
  "script": "skip",
  "install": "skip",
  "language": "python",
  "conditions": "v1",
  "global_env": "scrt={:secure=>\"CJr5vEewpazymBDeetBGjkIxMmr4GuvvxbdI/bcAyS+wBdfY8jt1XTVL/Gd/b7vZ1awczAgaDF+AZGWu8JetjQdsBGe6vd5ZitXjOs/M7Vim6LKDvyKKE231i5I7SqVp4v7btNRIROV0CrEWzJLhg3VXdXR968DluyW120e2eDnjeDti5EjLgQfYfIoDZzWrvKVyAB9zLkjUE/5ark9JpD7a6y6JfiMkKGFLzAe55tQlgFxVKQYoxpzFofVucwGdl9rMlDUsvV8c6GP9vjesv21R8mfHo4gtoRTWci4yM+8JSHIUQnostP0mZ3e6LiC71C9OVfgUcFvG+3ikomDOTZDsnahn+YbU4SAgI6WAajjoLE24F/W/pkELxT9MKURfMMDwsUH7epIoC9NBjLK4sYwQQmv7WtlcyGbOVl3T5o/Hn9MwuYhfNqmyEKQTdrB6hxOm1kIUVNouBdKT9CBWCeUXogVuAI0cpCDNikecD8tHFNT7V5ECapuijozXSiRyrv24ygZG14HAiABjbAKVCGgWx7kdCzch13muMiUiSk2/sN1EMDzzAgK3StVSuKhA/ItZKkEOubKYl/stgaB0m4Wm55IeFFOD2wzHDgWbglDhlxFPYOzrogUEnV+digcerXbFTiB6WXB4wmr6hssDhWo7u90MF3gBOFV/BZkD7As=\"}",
  "before_deploy": [
    "echo \"${scrt:0:2}..${scrt:31}\""
  ]
}
```

**Comment by webknjaz** [comment]
@svenfuchs ^

**Comment by svenfuchs** [comment]
@webknjaz Sorry we have both completely missed your PR! :(

Are you still seeing this issue? Or have you closed it because we've fixed things in the meantime?

**Comment by webknjaz** [comment]
@svenfuchs I think that it's still the case but I also confused what was documented.

It's just because this syntax works in provider passwords but not env vars.

Let's try rerunning this PR to find out.

In general, it'd be nice to support this case regardless of whether it worked before.

**Comment by webknjaz** [comment]
I rebased it.

**Comment by webknjaz** [comment]
Oh, this file was moved elsewhere. I hope the testrunner will still pick it up. The test I was adding originally was `given a hash with secure values`. I don't have time to dig into Ruby now but it should be a good pointer for you to take a look in case you need it.

**Comment by svenfuchs** [comment]
@webknjaz thank you! i'll have a look asap.

**Comment by svenfuchs** [comment]
@webknjaz this has taken quite a while now but i am finally getting back to travis-yml, so i've had a chance to have a closer look.

at first i thought your expectation was right, but after digging a little deeper, i don't think this has anything to do with travis-yml, but never was or is supported. on `env` this works:

```yaml
env:
  - secure: 'encrypted KEY=value'
```

while this does not:

```yaml
env:
  FOO: 
    secure: 'encrypted value'
```

i understand your expectation, and i'll have a look into changing this. i have already allowed this case in travis-yml:

image
http://config.travis-ci.org

i'll close your PR here, but keep #78 open for now.

**Comment by webknjaz** [comment]
Great, thanks!

**Comment by svenfuchs** [comment]
@webknjaz I have a fix for this which currently is behind a feature flag based on the repo owner name. if you'd like to try this out please let me know, and which repo owner name to enable. Or you can wait for another week or two until we have this rolled out to everyone.

**Comment by webknjaz** [comment]
I'll just wait, thanks!

**Pull request closed without merging**
