### PR TITLE
Adding more options available to AWS Lambda deployment

### PR DESCRIPTION
**Pull request by mboudreau**
Will work in unison with changes done to dpl: https://github.com/travis-ci/dpl/pull/676

### CODE REVIEW

**Comment by carlad** [comment]
thanks @mboudreau !

**Comment by mboudreau** [comment]
@carlad
When will it be deployed and available on Travis?

**Comment by svenfuchs** [comment]
@mboudreau This repository contains our work on a new, strict build config parser that is not yet in production. Your PR is great help to us as we need to stay up to date with recent development in tooling.

Are these options not currently propagating properly to the build script when you set them in your .travis.yml file?

**Comment by mboudreau** [comment]
@svenfuchs Ah, that's interesting, I thought this was in use right now.

The reason is because I have another PR for dpl to add these options for the Lambda provider, however, when I add these extra properties, they don't seem to come through.  I've added a line of code in my PR to output the provider and all the options, but some of the more complicated types aren't coming through.  I had thought it was because of this project.

For instance, I have this in my travis config:

```
- provider: lambda
  skip_cleanup: true
  edge:
    source: mboudreau/dpl
    branch: master
  function_name: some-lambda
  module_name: index
  handler_name: handler
  role: arn:aws:iam::some-role
  zip: package.zip
  region: ap-southeast-2
  runtime: nodejs6.10
  timeout: 60
  environment_variables:
    SF_USERNAME: "username"
    SF_PASSWORD: "password"
  kms_key_arn: "arn:something"
  dead_letter_arn: "arn:something"
  tracing_mode: "update"
  subnet_ids:
    - subnet1
    - subnet2
  security_group_ids:
    - group1
    - group2
  access_key_id: "some-key"
  secret_access_key: "some-secret"
```
And in the provider, it outputs:
```
Provider Lambda with options {:app=>"some-lambda", :key_name=>"testing-docker-something", :access_key_id=>"some-key", :dead_letter_arn=>"arn:something", :function_name=>"some-lambda", :handler_name=>"handler", :kms_key_arn=>"arn:something", :module_name=>"index", :provider=>"lambda", :region=>"ap-southeast-2", :role=>"arn:aws:iam::some-role", :runtime=>"nodejs6.10", :secret_access_key=>"some-secret", :security_group_ids=>["group1", "group2"], :skip_cleanup=>true, :subnet_ids=>["subnet1", "subnet2"], :timeout=>"60", :tracing_mode=>"update", :zip=>"package.zip", :fold=>true}
```
As I'm sure you can see, it's missing the environment variables that I've set.  I'm guessing it's because it's an object and not a simple string or list like the others. Any ideas?

**Pull request merged**
