### PR TITLE
Shared build workspaces

### PR DESCRIPTION
**Pull request by svenfuchs**

### CODE REVIEW

**Comment by kadirselcuk** [comment]
Merhaba Selam Travis-yml çekme istediğimi, Çalışma alanları hakkında şuan. Diğer dallar için hangi yönergesi vardır, teşekkürler

**Review by native-api — CHANGES_REQUESTED** [review]
The code looks obsolete. According to https://docs.travis-ci.com/user/using-workspaces/#configuration, there's also `use` clause, and `create` is now a map.

**Review by vitalied — CHANGES_REQUESTED** [review]
@GbArc pls fix conficts and add link to ticket in PR description, if any

**Comment by michal-at-travisci** [comment]
What about `use` and `create` remark, @vitalied ?

**Comment by vitalied** [comment]
@michal-at-travisci reverted the code and reopened a new PR to fix the code https://github.com/travis-ci/travis-yml/pull/254

**Pull request merged**
