### PR TITLE
update r_spec.rb with bioc_check, closes #55

### LINKED ISSUE #55: r: Add `bioc_check` to namespace
See https://github.com/travis-ci/travis-build/pull/1384

### PR DESCRIPTION
**Pull request by LiNk-NY**
Hi Joep, @joepvd 

I am not sure what files need to be modified here but I've started with this file. 
Please check it. I'll be happy to make any further modifications. 

Regards,
Marcel

### CODE REVIEW

**Comment by LiNk-NY** [comment]
All checks look good! :+1: 
@joepvd

**Comment by LiNk-NY** [comment]
Hi @jimhester @BanzaiMan 
Could you review and approve if it looks good?
Thanks!

**Comment by LiNk-NY** [comment]
Just to follow up, @joepvd. R lang builds are not working. Please review. @jimhester @BanzaiMan @svenfuchs @joecorcoran

**Comment by jimhester** [comment]
LGTM

**Comment by LiNk-NY** [comment]
Hi Joe, @joecorcoran 
Thanks for taking a look at it. I have updated the file. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Any updates Joe? @joecorcoran 
Thanks!

**Comment by joecorcoran** [comment]
Thanks all – deploying to production now. 🚀

**Pull request merged**
