### PR TITLE
Add support for Homebrew addon

### PR DESCRIPTION
**Pull request by mjm**
Added tests similar to what I found for the apt addon. My main outstanding question is: is there a way to make `brewfile` come in as a string or a bool depending on what is provided?

### CODE REVIEW

**Comment by mjm** [comment]
The brewfile key can either be true, indicating to use a custom Brewfile with the default file name, or it can be a string specifying what the name of the file is in case it’s not the default. So it can’t just be a bool or we’ll lose information.

**Comment by joecorcoran** [comment]
@mjm Okay cool, in that case we can specify that in a way that the boolean comes through as a proper boolean.

```
map :brewfile, to: [:bool, :scalar]
```

Shall I make that change on this branch, or would you like to?

**Comment by mjm** [comment]
Unfortunately, that change doesn't seem to work. Putting `:bool` first in the list means every string gets coerced into a bool, and the specs fail.

**Comment by mjm** [comment]
Yay! This is deployed in production and seems to be working.

**Comment by carlad** [comment]
Nice one Matt :)

**Pull request merged**
